# WhatATheme
markdown: kramdown

# URL of the Site
url: ''
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl: 

# Title of the Site
title: Glarner Berggeiss - Berglauf in Braunwald
# Description of the Site
description: Das Lauferlebnis in der Glarner Bergwelt
# URL of Image of the Site
site-image: /gb_page_dev/assets/images/meta.jpg
# Keywords of the Site
site-keywords: Site, Template, Theme
# URL for the Image of custom Favicon
favicon-url: 

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
heroimage: /gb_page_dev/20_ott.jpg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940

# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: glarnerberggeiss@bluewin.ch
facebook_username: glarnerberggeiss
instagram_username: glarnerberggeiss


# Google Analytics
google-analytics: UA-163806439-1

# Disqus
disqus-shortname: thedevslot

# Name of the Author
author-name: Glarner Berggeiss 2023
# URL for the Image of the Author
author-image: /gb_page_dev/geiss.jpg
# 60 Words About the Author
author-about: Nach drei erfolgreichen Jahren geht die Glarner Berggeiss diesen Sommer in die nächste Runde und feiert bereits ihren vierten Geburtstag. Am 25. August am späten Nachmittag findet der Startschuss über verschiedene Strecken hoch von Linthal nach Braunwald statt.
# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)author-url: https://github.com/thedevslot

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed

# Permalink
permalink: "blog/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
